version: "3"

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    volumes:
      - ./tmp/data/postgresql:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=authenticaiton-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=authenticaiton-app